<?php
/**
 * Script para corrigir o autoloader do Composer
 * 
 * Este script verifica e corrige o mapeamento do namespace Google\
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);
header('Content-Type: text/html; charset=utf-8');

echo "<h1>🔧 Correção do Autoloader</h1>";
echo "<hr>";

// Verificar se autoload_psr4.php existe
$psr4File = __DIR__ . '/vendor/composer/autoload_psr4.php';
if (!file_exists($psr4File)) {
    die("✗ Arquivo autoload_psr4.php não encontrado");
}

echo "<h2>1. Verificando mapeamento atual</h2>";
$psr4 = require $psr4File;
echo "<pre>";
echo "Namespace Google\\ mapeado para:\n";
if (isset($psr4['Google\\'])) {
    foreach ($psr4['Google\\'] as $path) {
        echo "  - " . htmlspecialchars($path) . "\n";
    }
} else {
    echo "  - NÃO ENCONTRADO\n";
}
echo "</pre>";

// Verificar onde a biblioteca realmente está
echo "<h2>2. Procurando biblioteca Google API Client</h2>";
$possiblePaths = [
    __DIR__ . '/vendor/google/apiclient/src',
    __DIR__ . '/vendor/google/apiclient/src/Google',
    __DIR__ . '/src',
    __DIR__ . '/src/Google'
];

$foundPath = null;
foreach ($possiblePaths as $path) {
    $clientFile = $path . '/Client.php';
    if (file_exists($clientFile)) {
        echo "✓ Encontrado: " . htmlspecialchars($clientFile) . "<br>";
        $foundPath = dirname($path);
        break;
    }
}

if (!$foundPath) {
    echo "✗ Biblioteca Google API Client NÃO encontrada<br>";
    echo "<br>";
    echo "<h2>❌ Problema Identificado</h2>";
    echo "<p>A biblioteca principal <code>google/apiclient</code> não foi encontrada.</p>";
    echo "<p><strong>Solução:</strong></p>";
    echo "<ol>";
    echo "<li>A biblioteca Google API PHP Client precisa ter a pasta <code>vendor/google/apiclient/</code></li>";
    echo "<li>Faça upload da biblioteca completa, incluindo:</li>";
    echo "<ul>";
    echo "<li><code>vendor/google/apiclient/</code> (biblioteca principal)</li>";
    echo "<li><code>vendor/google/apiclient-services/</code> (já existe)</li>";
    echo "<li><code>vendor/google/auth/</code> (já existe)</li>";
    echo "</ul>";
    echo "</ol>";
    exit;
}

echo "<h2>3. Corrigindo autoloader</h2>";

// Ler o arquivo atual
$content = file_get_contents($psr4File);
$psr4 = require $psr4File;

// Corrigir o mapeamento
$correctPath = __DIR__ . '/vendor/google/apiclient/src';
if (!isset($psr4['Google\\']) || !in_array($correctPath, $psr4['Google\\'])) {
    echo "Corrigindo mapeamento...<br>";
    
    // Remover mapeamento incorreto
    if (isset($psr4['Google\\'])) {
        $psr4['Google\\'] = array_filter($psr4['Google\\'], function($path) use ($correctPath) {
            return $path !== __DIR__ . '/src';
        });
    }
    
    // Adicionar mapeamento correto
    if (!isset($psr4['Google\\'])) {
        $psr4['Google\\'] = [];
    }
    
    if (!in_array($correctPath, $psr4['Google\\'])) {
        $psr4['Google\\'][] = $correctPath;
    }
    
    // Salvar arquivo
    $newContent = "<?php\n\n// autoload_psr4.php @generated by Composer\n\n\$vendorDir = dirname(dirname(__FILE__));\n\$baseDir = dirname(\$vendorDir);\n\nreturn " . var_export($psr4, true) . ";\n";
    
    if (file_put_contents($psr4File, $newContent)) {
        echo "✓ Autoloader corrigido com sucesso!<br>";
    } else {
        echo "✗ Erro ao salvar autoloader (pode ser problema de permissão)<br>";
    }
} else {
    echo "✓ Mapeamento já está correto<br>";
}

echo "<br>";
echo "<h2>4. Testando após correção</h2>";

// Recarregar autoloader
require_once __DIR__ . '/vendor/autoload.php';

if (class_exists('Google\Client')) {
    echo "✓ Classe Google\\Client encontrada!<br>";
    try {
        $client = new \Google\Client();
        echo "✓ Google\\Client instanciado com sucesso!<br>";
    } catch (Exception $e) {
        echo "✗ Erro ao instanciar: " . htmlspecialchars($e->getMessage()) . "<br>";
    }
} else {
    echo "✗ Classe Google\\Client ainda não encontrada<br>";
    echo "<p>Pode ser necessário fazer upload da biblioteca completa.</p>";
}

echo "<br>";
echo "<hr>";
echo "<p><a href='diagnostico-google-api.php'>Executar diagnóstico novamente</a></p>";
?>

